version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: postgis_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:    # waith for the database to be ready
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 10

  web:
    build: .
    container_name: django_app
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py makemigrations &&
            python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
