# Generated by Django 5.1.7 on 2025-03-11 14:25

import django.contrib.gis.db.models.fields
from django.contrib.gis.gdal import DataSource
from django.contrib.gis.utils import LayerMapping
from django.db import migrations, models


def get_general_timezones(apps, schema_editor):
    TimezoneGeneral = apps.get_model('web', 'TimezoneGeneral')

    meridian = 180
    utc_hours = 12
    while utc_hours >= -12:
        step = 7.5 if meridian == 180 or meridian == -172.5 else 15
        name = f'UTC+{utc_hours}' if utc_hours >= 0 else f'UTC{utc_hours}'

        general_timezone = TimezoneGeneral(
            name=name,
            long_min=meridian - step,
            long_max=meridian,
        )
        general_timezone.save()

        utc_hours -= 1
        meridian -= step


def save_tz_shapefile(apps, schema_editor):
    file_path = 'data/tz_world.shp'
    TimezoneShape = apps.get_model('web', 'TimezoneShape')
    ds = DataSource(file_path)
    layer = ds[0]
    field_name = layer.fields[0]
    # Mapping between the model fields and the shapefile fields
    mapping = {
        'name': field_name,
        'poly': 'POLYGON',
    }

    # LayerMapping instance
    lm = LayerMapping(TimezoneShape, file_path, mapping)
    lm.save(strict=True, verbose=True)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='TimezoneGeneral',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('long_min', models.FloatField()),
                ('long_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TimezoneShape',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.RunPython(get_general_timezones, lambda a, s: None),
        migrations.RunPython(save_tz_shapefile, lambda a, s: None),
    ]
